import Head from 'next/head'
import styles from '@/styles/blog/Articles.module.sass'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import fetchArticles from '@/services/blog' // 導入 fetchArticles

const ArticlesList = () => {
  const [articles, setArticles] = useState([])
  useEffect(() => {
    const getArticles = async () => {
      const data = await fetchArticles() // 使用 fetchArticles
      if (data) {
        setArticles(data)
      }
    }

    getArticles()
  }, [])

  return (
    <>
      <Head>
        <title>文章列表</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
        <div className="d-flex align-items-center">
          <div className={styles.h1}>文章列表</div>
          <div>
            <Link
              href="/article/publish"
              className="btn btn-primary btn-sm ms-2"
            >
              發表文章
            </Link>
          </div>
          <div>
            <Link href="/" className="btn btn-primary btn-sm ms-2">
              回首頁
            </Link>
          </div>
        </div>
        <div>
          {articles.map((article) => (
            <div key={article.article_id} className="card my-2">
              <div className="card-body">
                <h5 className="card-title">{article.article_title}</h5>
                <h6 className="card-subtitle mb-2 text-muted">
                  作者: {article.author}
                </h6>
                <div className="d-flex justify-content-end">
                  <Link
                    className="btn btn-primary"
                    href={`/article/${article.id}`}
                  >
                    閱讀更多
                  </Link>
                </div>
              </div>
            </div>
          ))}
        </div>
      </main>
    </>
  )
}
export default ArticlesList
