import Head from 'next/head'
import styles from './publish-form.module.scss'
import Link from 'next/link'
import Myeditor from '@/components/blog/article-add/Myeditor'
import { useState, useEffect } from 'react'
import { useRouter } from 'next/router'
import { publish } from '@/services/blog'

export default function PublishForm() {
  const [editorLoaded, setEditorLoaded] = useState(false)
  const [title, setTitle] = useState('')
  const [author, setAuthor] = useState('')
  const [data, setData] = useState('')
  const router = useRouter()
  const [category, setCategory] = useState([]) // 新增的 state
  const categories = ['蛋糕', '泡芙', '餅乾', '教學']

  const saveToDb = async (event) => {
    event.preventDefault()
    try {
      const response = await publish({ title, author, article: data, category })
      console.log(response)
      if (response.status === 200) {
        alert('資料寫入成功')
        router.push('/blog')
      } else {
        alert(`寫入失敗: ${response.data.message}`)
      }
    } catch (error) {
      console.error(error)
    }
  }
  useEffect(() => {
    setEditorLoaded(true)
  }, [])
  
  const handleCategoryChange = (event) => {
    const selectedCategory = event.target.value
    if (category.includes(selectedCategory)) {
      setCategory(category.filter((cat) => cat !== selectedCategory))
    } else {
      setCategory([...category, selectedCategory])
    }
    console.log(setCategory);
  }
  return (
    <>
      <Head>
        <title>發表文章</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
        <div className="d-flex align-items-center">
          <div className={styles.h1}>發表文章 </div>
          <div>
            <Link href="/article" className="btn btn-primary btn-sm ms-2">
              回文章列表
            </Link>
          </div>
        </div>
        <div className="input-group mb-2">
          <span className="input-group-text">文章標題</span>
          <input
            className="form-control"
            type="text"
            name="title"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
          />
        </div>
        <div className="input-group mb-2">
          <span className="input-group-text">作者</span>
          <input
            className="form-control"
            type="number"
            name="author"
            value={author}
            onChange={(e) => setAuthor(e.target.value)}
          />
        </div>
        <div className="">
          <div className="">
            <span className="">類別 ：</span>
            {categories.map((cat) => (
              <label key={cat}>
                <input
                  type="checkbox"
                  value={cat}
                  name="category"
                  checked={category.includes(cat)}
                  onChange={handleCategoryChange}
                />
                {cat}
              </label>
            ))}
          </div>
        </div>
        <Myeditor
          name="article"
          onChange={(data) => {
            setData(data)
          }}
          editorLoaded={editorLoaded}
        />
        <div className="input-group mt-2">
          <button className="btn btn-primary ms-auto" onClick={saveToDb}>
            送出
          </button>
        </div>
      </main>
    </>
  )
}
